# Generated by Django 5.1.1 on 2024-11-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('area', models.CharField(choices=[('kay', 'kayole'), ('buru', 'buruburu'), ('lucky', 'luckysummer'), ('kan', 'kangemi'), ('baba', 'babadogo')], max_length=50)),
                ('has_water_daily', models.BooleanField(default=True)),
            ],
        ),
    ]
